server:
  port: 8080

jwt:
  secret: dW1jLW5hZGFtc3BhY2UtcHJvamVjdC1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWtleS1mb3ItZGlhcnktYXBwbGljYXRpb24K
  # Access Token 유효 시간 (30분)
  access-token-expiration-time: 1800000
  # Refresh Token 유효 시간 (2주)
  refresh-token-expiration-time: 1209600000


logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/uoucapstone?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
     username: root
     password: 1234

  jpa:
    hibernate:

      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


#?뚯뒪??: https://kauth.kakao.com/oauth/authorize?client_id=275b2717e98d58ac245a1ba255f57d03&redirect_uri=http://localhost:8080/login/oauth2/code/kakao&response_type=code

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 275b2717e98d58ac245a1ba255f57d03
            client-secret: JChF9Fptvsdkky2Lhp18vEcouYFuOuBv
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



springdoc:
  # 1. API
  api-docs:
    path: /api-docs   # API

  # 2. Swagger UI
  swagger-ui:
    path: /swagger-ui.html   # Swagger UI
    disable-swagger-default-url: true # Spring Boot
    display-request-duration: true  # API

  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  info:
    title: AI튜터
    description:
    version: v1.0.0




# =================================================================================
# AI SERVICE CONFIGURATION
# =================================================================================
ai:
  service:
    base-url: https://plutean-clement-apheliotropically.ngrok-free.dev/
    secret-key: "YOUR_SUPER_SECRET_AI_KEY_12345" # ai-service(FastAPI)??二쇱냼

